spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://gocar-db.cgy0y1fgfsud.us-east-1.rds.amazonaws.com:3305/gocar
    #    A URL acima cont√©m o nome do container em que o BD se encontra (mysql_server_ecommerce)
    username: admin
    password: 98164123
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
  sql:
    init:
      continue-on-error: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher